### ISSUE TITLE
Update notification to mention that the rate limit only applies for shared aliases

### ISSUE THREAD

**Issue by Jayto1** [anonaddy/anonaddy.com#13]
![image](https://user-images.githubusercontent.com/79473923/152412901-55e8d2ef-544e-4b35-80e2-c33c95f8cfa4.png)

**Comment by Jayto1** [comment]
Oh and on the FAQ too :)

**Comment by willbrowningme** [comment]
That limit is on the number of new aliases that can be created for each account per hour and depends on your plan.

https://anonaddy.com/faq/#is-there-a-limit-to-how-many-aliases-i-can-create-per-hour

It applies to any kind of alias.

**Comment by Jayto1** [comment]
@willbrowningme I'm a bit confused then, I saw this post today and it seems that you agreed that there is no limit for standard aliases.
https://www.reddit.com/r/AnonAddy/comments/sj8hek/what_happens_if_you_reach_your_limit_for_creating/

**Comment by willbrowningme** [comment]
That was referring to the total number of aliases limit. 

The number of aliases that can be created per hour is a completely separate limit.

**Comment by Jayto1** [comment]
Oh ok, I understand now, sorry for the confusion.
