### ISSUE TITLE
Missing Plans?

### ISSUE THREAD

**Issue by asimplechap** [anonaddy/anonaddy.com#18]
Sorry again for re submitting this one.  Thank you for the assist on getting the .com stuff working.

Here are some notes for others
`mkdir /var/www/example.com

cd /var/www

git clone https://github.com/anonaddy/anonaddy.com.git

cd /var/www/example.com

composer install --prefer-dist --no-dev -o && npm install

npm run production`

I did want to ask, how can I set up different plans or plans like the main site?  Reason is I set this up for some friends and myself, BUT I know they will take advantage lol.  I need some pretty big numbers for emails and data but they do not.  I do not want them to have same level that I have.  Is this possible or is this something I need to bake in myself?

Thanks Will!

**Comment by willbrowningme** [comment]
anonaddy.com (the landing page) is completely separate from the web application (app.anonaddy.com).

If you are self-hosting you do not need the anonaddy.com (this repository) as it is only for information purposes.

If you want to have different plans and levels of usage etc. then you will have to bake that into the [web application](https://github.com/anonaddy/anonaddy) yourself as currently you can only set a global bandwidth limit, username limit etc.
