### ISSUE TITLE
Tor Hidden Service

### ISSUE THREAD

**Issue by TheUndeserving** [anonaddy/anonaddy.com#20]
Can there be a .onion site for Anonaddy to sign up, access the forwarding emails on and pay with to make that process a bit more anonymous?

**Comment by willbrowningme** [comment]
Thanks for the suggestion, this is already on the [roadmap](https://github.com/anonaddy/anonaddy/projects/1#card-56906846), I have a fair amount of things I need to do before this so I cannot give a date I'm afraid.

Closing this for now since it is already on the roadmap.
