### ISSUE TITLE
RSS feed for blog posts

### ISSUE THREAD

**Issue by sylph1o** [anonaddy/anonaddy.com#5]
Hi!

Is there a RSS feed for the blog posts? I know such feeds are sometimes hidden, but even trying to guess the URL yielded nothing.

If there is a feed, would it be possible to add a link to it on `anonaddy.com/blog/`?

**Comment by willbrowningme** [comment]
There is an atom feed here - [https://anonaddy.com/blog/feed.atom](https://anonaddy.com/blog/feed.atom)

Thanks for bringing this up though I thought I had a link somewhere but obviously don't. I'll add an icon to the footer shortly.

**Comment by willbrowningme** [comment]
Added in latest commit https://github.com/anonaddy/anonaddy.com/commit/44f845091bf8b713c10e1041020c6ec13d4a0760.
